config/routes.rb
Rails.application.routes.draw do
  get 'uploads/new'

  get 'uploads/create'

  get 'uploads/edit'

  get 'sessions/new'

  root 'main#index'

  get 'about' => 'main#about'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  get 'logout' => 'sessions#destroy'

  get 'signup' => 'users#new'

  post 'signup' => 'users#create'

  get 'users' => 'users#index'

  get 'results' => 'events#results'

  post 'users/:id' => 'users#follow'

  post 'remove' => 'users#remove'

  resources :users
  resources :events

  get '/:error' => 'main#error'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_and_belongs_to_many :users
  validates :event_id, :date, :location, :artist, presence: true

end

app/models/events_users.rb
class EventsUsers < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User", :foreign_key => "friend_id"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :events

  # tell ActiveRecord that a user has_many friendships
  has_many :friendships
  has_many :friends, :through => :friendships

  # has_many :followers, class_name: "User",
  #                         foreign_key: "friend_id"
 
  # belongs_to :friend, class_name: "User"

  validates :email,
  presence: true,
  uniqueness: {case_sensitive: false},
  email: true

  validates :name,
  presence: true,
  length: {maximum: 20}

  has_secure_password

  validates_presence_of :password,
  confirmation: true,
  :if => lambda {|user| user.password_digest_changed?}

	def self.authenticate email, password
		User.find_by_email(email).try(:authenticate, password)
	end

 
    
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :current_user

	def is_authenticated?
  	unless current_user
  		flash[:danger] = 'You are not logged in!'
  		redirect_to root_path
  	end
  end

  def current_user
  	@current_user ||= User.find_by_id(session[:user_id])
  end
end

app/controllers/events_controller.rb
require 'rest-client'
require 'json'

class EventsController < ApplicationController
  attr_accessor :event_id, :date, :locations, :artist, :zip, :datepicker_start_date, :datepicker_end_date

  def index
  # @events = Event.all
  end

  def results
    @events = Event.new
    @startDate = params[:datepicker_start_date].to_datetime
    @endDate = params[:datepicker_end_date].to_datetime
    @zipCode = params[:zip].to_i > 0 ? params[:zip].to_i : 98101
    @jbkey = ENV['JAMBASE_API_KEY']

    puts "****StartDate********"
    puts @startDate
    puts "****EndDate********"
    puts @endDate
    puts "****zipCode********"
    puts @zipCode

    response = RestClient.get "http://api.jambase.com/events", {:params => {:api_key => @jbkey, :o => 'json', :page => 0, :zipCode => @zipCode, :startDate => @startDate, :endDate => @endDate}}
    @results = JSON.parse(response)

    puts "**********************"
    puts @results
    puts "**********************"


  end

  def show

  end

  
  def new
    @events = Event.new
  end

  def create
    @user = User.find(session[:user_id])
    @event = Event.find_by(event_id: params[:event_id])

    # If Songkick event ID is already in database
    if @event
      @user.events << @event
    else
      @event = Event.create event_params
      @user.events << @event
    end
    flash[:success] = 'Event was saved to your calendar!'
    redirect_to events_path
  end

  def destroy
    Event.find(params[:id]).delete
    redirect_to events_path
  end


  private

  def event_params
    params.require(:event).permit(:event_id, :date, :location, :artist, :price)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.authenticate login_params['email'], login_params['password']

  	if(user)
  		session[:user_id] = user.id
  		flash[:success] = 'You have successfully logged in!'
  		redirect_to user
  	else
  		flash[:danger] = 'Invalid email or password!'
  		redirect_to root_path
  	end
  end

  def destroy
  	session[:user_id] = nil
  	flash[:success] = 'You have successfully logged out!'
  	redirect_to root_path
  end

  private 

  def login_params
  	params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    search = params[:search]
      if search
        @users = User.where('lower(name) = ?', search.downcase)
      elsif search == nil
        @users = User.all
      end
  end

  def create
    user = User.create user_params
    
    if (params[:user][:picture])
      uploaded_path = params[:user][:picture].path
      cloud_file = Cloudinary::Uploader.upload(uploaded_path)
      user.cloud_id = cloud_file['public_id']

    else 
      user.cloud_id = 'no-user_sa25wv'
    end

    user.save
    
    if user
      session[:user_id] = user.id
      flash[:success] = 'You have successfully logged in!'
      redirect_to user
    else
      flash[:danger] = 'Invalid email or password!'
      redirect_to root_path
    end
  end

  def new
    @user = User.new
  end
  
  def show
    require 'date'
    @user = User.find params[:id]
    @events = @user.events
    @friend = @user
    @friends = @user.friends
    @followers = Friendship.includes(:user).where(:friend_id => @user.id)
    
    today = Date.today
    year = today.year
    month = today.mon
    day = 01
    month_names = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
    gon.month = month_names[month - 1]
    gon.year = year
    startDate = Date.new(year, month, day)
    week = startDate.wday == 0 ? startDate.cweek + 1 : startDate.cweek

    arr = Array.new(5) { Array.new(7) { {"date" => 0, "events" => []} } }

    for i in 1..5
      for j in 1..7
        if j == 1

          date = Date.commercial(year, week + i - 2, 7)
          arr[i-1][j-1]["date"] = (date.mon == month) ? date.mday : ''
          @events.each do |e|
            if e.date == date
              arr[i-1][j-1]["events"] << e
            end
          end

        else

          date = Date.commercial(year, week + i - 1, j - 1)
          arr[i-1][j-1]["date"] = (date.mon == month) ? date.mday : ''
          @events.each do |e|
            if e.date == date
              arr[i-1][j-1]["events"] << e
            end
          end

        end
      end
    end

      gon.weeks0 = arr[0].to_json
      gon.weeks1 = arr[1].to_json
      gon.weeks2 = arr[2].to_json
      gon.weeks3 = arr[3].to_json
      gon.weeks4 = arr[4].to_json

  end

  def update
    userParams = params.require(:user).permit(:name, :email, :cloud_id)
    u = User.find_by_id(@current_user.id)

    if (params[:user][:picture])
      uploaded_path = params[:user][:picture].path
      cloud_file = Cloudinary::Uploader.upload(uploaded_path)
      u.cloud_id = cloud_file['public_id']

    else 
      u.cloud_id = u.cloud_id
    end
    
    u.update_attributes(userParams)
    redirect_to '/users/' + @current_user.id.to_s
  end

  def edit
    @user = User.find params[:id]
    @users = User.all
  end

  def destroy
    user = User.find(params[:id])
    user.events.clear
    user.delete
    redirect_to root_path
  end

  def follow
    friendid = params[:user][:user_id]
    friend = User.find_by_id(friendid)
    friendship = Friendship.find_or_create_by(:user => @current_user, :friend => friend)
    flash[:success] = 'You are now following ' + friend.name + '!'
    redirect_to users_path
  end

  def remove

    user = User.find(params[:user_id])
    event = user.events.find(params[:event_id])

    # removes a specific event from a user's calendar (event stays in the db)
    user.events.delete(event)
    redirect_to '/users/' + @current_user.id.to_s

  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :cloud_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<div class='container'>
  <div class='page-header row'>
    <div class='col-md-6'>
      <h1><span id='concert-search'>Search for Shows</span></h1>
    </div>

    <div class='col-md-6 search-bar'>
      <%= bootstrap_form_tag url: results_path, :method => 'get' do |f| %>
      <div class="input-group input-daterange" id="datepicker">
         <h4><%= f.text_field :datepicker_start_date, label: "Search by Date:", placeholder: "Enter Start Date", 'data-behaviour' => 'datepicker', required: true %></h4>
         <!-- <input type="string" class="input-small" name="datepicker_start_date" /> -->
         <h4><%= f.text_field :datepicker_end_date, hide_label: true, placeholder: "Enter End Date", 'data-behaviour' => 'datepicker', required: true %></h4>
         <!-- <input type="string" class="input-small" name="datepicker_end_date" /> -->
      </div> 

      <div class='search-bar' id="zip-search">
        <h4><%= f.text_field :zip, label: "Search by Zip:", placeholder: "Enter Zip Code" %></h4>
        <%= f.primary 'Search for Concerts' %>
      <% end %>
      </div>
    </div>  
  </div>

  <div class="jambase"><br /><br />
  <a href="http://www.JamBase.com" title="JamBase Concert Search">
  <img src= "http://images.jambase.com/logos/jambase140x70.gif" alt="Search JamBase Concerts" border="0" /></a>
  <h5 class="white-text">Concert information provided by <a href="http://www.jambase.com">JamBase</a></h5>
  </div>
</div>

app/views/events/results.html.erb
<div class='container'>
  <div class='page-header row'>
    <div class='col-md-6'>
    <h1><span id='concert-search'>Concerts by Date/Location</span></h1>
    <%= link_to '&larr; Back'.html_safe, events_path, class: 'btn btn-primary back' %>
    </div>
    <div class='col-md-4 col-md-offset-2'>
      <div>
        <a href="http://www.JamBase.com" title="JamBase Concert Search">
        <img src= "http://images.jambase.com/logos/jambase140x70.gif" alt="Search JamBase Concerts" border="0" /></a>
        <h5 class="white-text">Concert information provided by <a href="http://www.jambase.com">JamBase</a></h5>
      </div>
    </div>
  </div>

  <% if @results["Info"]["TotalResults"] > 0 %>
    <h2 class="white-text"><%= @results["Events"][0]["Date"].to_date.strftime("%B %d, %Y") %></h2>
    <% @results["Events"].each do |e| %>
    <div class="well events-results">
      <h4>Date: <%= e["Date"].to_date.strftime("%B %d, %Y") %>
      </h4>
      <h4><% e["Artists"].each do |a| %>
          <%= a["Name"] %>
        <% end %>
      </h4>
      <h4><%= e["Venue"]["Name"] %>, <%= e["Venue"]["City"] %>, <%= e["Venue"]["StateCode"] %>
      </h4> 
      <h5 class="event-url"> <a href="<%= e["TicketUrl"] %>"><%= e["TicketUrl"] %></a></h4>

        <%= form_for @events, :method => 'post' do |event| %>
        <%= event.hidden_field :event_id, :value => e["Venue"]["Id"] %>
        <%= event.hidden_field :date, :value => e["Date"] %>
        <%= event.hidden_field :location, :value => e["Venue"]["Name"] %>
        <%= event.hidden_field :artist, :value => e["Artists"][0]["Name"] %>
        <%= event.hidden_field :price, :value => e["TicketUrl"] %>
        <%= event.submit class: 'btn' %>

      <% end %>
    </div>
    <% end %>
  <% else %>
    <h2 class="white-text"> No Results, Please Search Again </h2>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" media="screen" href="//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
	<link href='https://fonts.googleapis.com/css?family=Muli' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" href='https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css'>
	<title>Concrt</title>
  <%= include_gon  %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'partials/navbar' %>
	<%= render 'partials/flash' %>
	<%= render 'partials/signup' %>
	<%= render 'partials/login' %>
	<%= render 'partials/event_info'  %>

	<%= yield %>

	<script src="//netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
	<script src="//d3js.org/d3.v3.min.js" charset="utf-8"></script>
	<script>
	    var options = {
    		directionThreshold: 20,
    		slideSpeed: 500
			};

	    $('#panel-container').panelSnap(options);
	</script>
</body>
</html>

app/views/main/about.html.erb
<div class='container'>
	<div class='page-header row'>
		<h1 id='meet'>Meet Our Team</h1>
	</div>

	
		<div class='col-md-4 profile'>
			<h3>Chris Carlson</h3>
			<img class='profile-pic' src="<%= asset_path( 'chris.jpg' ) %>"  />
			<p class='profile-content'>Whether it's playing music or writing code, I am always creating. A drummer turned web dev, I feel that my musical background gives me a unique perspective on the tech industry. I love collaboration and creating as a team. Technologies I have experience with include Javascript, HTML, CSS, Node, Sequelize, Ruby, and SQL</br> 

			When I'm not coding you can find me playing music, enjoying the outdoors, or gaming</br>
			<a href='https://github.com/thecodingcarlson'><i class="fa fa-github fa-2x"></i></a>
			<a href='https://www.linkedin.com/in/thecodingcarlson'><i class="fa fa-linkedin-square fa-2x"></i></a>
			</p>

		</div>

		<div class='col-md-4 profile'>
			<h3>Sam French</h3>
			<img class='profile-pic' src="<%= asset_path( 'sam.jpg' ) %>" />
			<p class='profile-content'>
			I am a Seattle-based web developer who works in full-stack and back-end applications. I want to combine my analytical skills and creativity in order to solve problems. I am always listening to music and going to shows. I hope Concrt will be the perfect tool for finding concerts and sharing them with friends.</br>

			In my free time, I also enjoy hiking, rock climbing, and biking.</br>
			
			<a href='https://github.com/samofrench'><i class="fa fa-github fa-2x"></i></a>
			<a href='https://www.linkedin.com/in/sam-french-85076083'><i class="fa fa-linkedin-square fa-2x"></i></a>
			</p>
		</div>

		<div class='col-md-4 profile'>
			<h3>Beth Ernsberger</h3>
			<img class='profile-pic' src="<%= asset_path( 'beth.jpg' ) %>" />
			<p class='profile-content'>
			I’m a full-stack website developer who thrives on creative collaboration, learning about and creating websites with the latest technologies, and designing intuitive front-end functionality. My natural tendency for efficient organization (just call me "spreadsheet queen") led to my first enjoying database management and now lends itself well to creating efficiently coded and organized websites.</br> 

			When I'm not in front of my computer, you might find me hiking/snowshoeing the trails around Seattle, at Wednesday trivia night with my friends, or East Coast Swing dancing at the Century Ballroom.</br>
			<a href='https://github.com/bethburger42'><i class="fa fa-github fa-2x"></i></a>
			<a href='https://www.linkedin.com/in/marybethernsberger'><i class="fa fa-linkedin-square fa-2x"></i></a>
			</p>
		</div>
</div>

app/views/main/error.html.erb
<h1>An error occurred</h1>

app/views/main/index.html.erb
<div id='panel-container'>
	<section data-panel="first" class="first">
		<div class='s-div'>
			<div class='f-content'>
				<h1>Welcome to Concrt</h1>
				<h2>A place to find and discover local music</h2>
				<h3>scroll down to learn more</h3>
				<i class="fa fa-arrow-down fa-2x animated infinite pulse"></i>
			</div>
		</div>
	</section>

	<section data-panel="second" class="second">
		<div class='s-div'>
			<div class='s-content'>
				<h1>Discover Local Music</h1>
				<h2>Search and discover local shows near you.<br>
					Tap into your cities rich musical scene</h2>
					<i class="fa fa-arrow-down fa-2x animated infinite pulse"></i>
			</div>
		</div>
	</section>

	<section data-panel="third" class="third">
		<div class='s-div'>
			<div class='s-content'>
			<h1>Meet Up With Friends</h1>
			<h2>Follow your friends and see what shows<br>
			they are going to. Create a calendar and<br>
			share your show with others.</h2>
			<i class="fa fa-arrow-down fa-2x animated infinite pulse"></i>
			</div>
		</div>
	</section>

	<section data-panel="fourth" class="fourth">
		<div class='s-div'>
			<div class='t-content'>
				<h1>What Are You Waiting For?</h1>
				<h2>Sign up now and start seeing live music!</h2>
				<a><%= link_to 'Login', '#login', 'data-toggle' => 'modal', 'data-target' => '#login', class: 'btn btn-default btn-lg wb', id: 'wb-1'%></a>
				<a><%= link_to 'Sign-Up', '#signup', 'data-toggle' => 'modal', 'data-target' => '#signup', class: 'btn btn-default btn-lg wb', id: 'wb-2'%></a>
			</div>
		</div>
	</section>
	<div class='footer'>
		<h3><%= link_to 'About Us', about_path %></h3>
		<a href='https://github.com/TheCodingCarlson/concrt'><i class="fa fa-github fa-2x"></i></a>
	</div>
</div>

app/views/partials/_delete.html.erb
<div class="modal custom fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog">
    <div class="modal-content">
    	<div class='m-div'>
	    	<h1>Are You Sure?</h1>
	    	<%= link_to '<i class="fa fa-trash-o"></i> Delete Profile'.html_safe, @user, class: 'btn btn-danger', method: :delete %>
	    	<button class="btn btn-primary" data-dismiss="modal">Close</button>
			</div>
    </div>
  </div>
</div>

app/views/partials/_edit.html.erb
<div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog">
    <div class="modal-content">
    <div class='m-div'>
	    	<h1>Edit Your Profile</h1>
						<%= bootstrap_form_for @user do |u| %>
					  <%= u.text_field :name %>
						<%= u.text_field :email %>
						<%= u.file_field :picture %>
					  <%= u.primary %>
					  <button class="btn btn-default" data-dismiss="modal">Close</button>
				<% end %>
			</div>
    </div>
  </div>
</div>

app/views/partials/_event_info.html.erb
<div class="modal custom fade" id="event_info" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog">
    <div class="modal-content">
    	<div class='m-div'>
		  	<h1 class="event-artist"></h1>
			<p class="event-date"></p>
			<p class="event-location"></p>

			<% if (@current_user == @user) %>
				<%= bootstrap_form_tag url: '/remove' do |f| %>
					<%= f.hidden_field :user_id, value: @current_user ? @current_user.id : -1 %>
					<%= f.hidden_field :event_id, class: 'event-id' %>
					<%= f.primary 'Remove Event' %>
				<% end  %>
			<% end %>
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		</div>
    </div>
  </div>
</div>

app/views/partials/_flash.html.erb
<% flash.each do |type, message| %>
	<div class='alert alert-<%=type%>'>
		<%= message %>
	</div>
<% end %>

app/views/partials/_login.html.erb
<div class="modal custom fade" id="login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog">
    <div class="modal-content">
    	<div class='m-div'>
	    	<h1>Login</h1>
				<%= bootstrap_form_for :user, url: login_path do |f| %>
					<%= f.text_field :email, placeholder: 'Email', class: 'form-control' %>
					<%= f.password_field :password, placeholder: 'Password', class: 'form-control'%>
					<%= f.primary 'Log In '%>
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				<% end %>
			</div>
    </div>
  </div>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-fixed" role="navigation">
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a id='brand' class="navbar-brand" href="/">Concrt</a>
	</div>

<% if (@current_user) %>
	<div class="collapse navbar-collapse navbar-ex1-collapse">
		<ul class="nav navbar-nav navbar-right">
			<li class='nav-links'><%= link_to 'Me', {:controller => "users", :action => "show", :id => @current_user.id } %></li>
			<li class='nav-links' id='nl'><%= link_to 'Users', users_path %></li>
			<li class='nav-links' id='nl'><%= link_to 'See a Show', events_path %></li>
			<li class='nav-links' id='nl'><%= link_to 'Logout', logout_path %></li>
		</ul>
	</div>
 <% else %>
 		<div class="collapse navbar-collapse navbar-ex1-collapse">
		<ul class="nav navbar-nav navbar-right">
			<li class='nav-links' id='nl'><%= link_to 'Users', users_path %></li>
			<li class='nav-links' id='nl'><%= link_to 'See a Show', events_path %></li>
			<li class='nav-links' id='nl'><%= link_to 'Login', '#login', 'data-toggle' => 'modal', 'data-target' => '#login' %></li>
			<li class='nav-links' id='nl'><%= link_to 'Sign-Up', '#signup', 'data-toggle' => 'modal', 'data-target' => '#signup' %></li>
		</ul>
	</div>
<% end %>
</nav>

app/views/partials/_signup.html.erb
<div class="modal fade" id="signup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog">
    <div class="modal-content">
    <div class='m-div'>
	    	<h1>Sign-Up</h1>
					<%= bootstrap_form_for :user, url: signup_path do |f| %>
						<%= f.text_field :name, placeholder: 'Name', required: true %>
						<%= f.text_field :email, placeholder: 'Email', required: true %>
						<%= f.file_field :picture %>
						<%= f.password_field :password, placeholder: 'Password', required: true %>
						<%= f.password_field :password_confirmation, placeholder: 'Re-Type Password', required: true %>
						<%= f.primary 'Sign Up'%>
						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				<% end %>
			</div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class='container'>
	<div class='page-header row'>
		<div class='col-md-8'>
				<h1><span id='network'>Network</span>
				<% unless (@current_user) %>
					<small id='u-link'>- <%= link_to 'Sign-Up Today!', '#signup', 'data-toggle' => 'modal', 'data-target' => '#signup'%></small></h1>
					<% end %>
			</div>
			<div class='col-md-3 search-bar'>
				<%= bootstrap_form_tag url: '/users', method: 'GET' do |f| %>
					  <%= f.text_field :search, placeholder: 'Search Users', hide_label: true,required: true %>
			</div>
			<div class='col-md-1 search-button'>
					 <%= f.submit "Search" %>
			</div>
				<% end %>
	</div>

	<div class='row'>
		<% @users.each do |user| %>
			<div class='col-md-2 user'>
				<%= cl_image_tag(user.cloud_id,
      	:width => 400, :height => 400, :crop => :fill, :gravity => :face) %>
				<h3><%= link_to user.name, user %></h3>
			</div>
		<% end %>
	</div>

</div>

app/views/users/show.html.erb
<%= render 'partials/delete' %>
<%= render 'partials/edit' %>

<div class='container'>
	<div class='page-header'>
		<h1 class='user-name'><%= @user.name %></h1>
			<% if @current_user && @current_user.id != @user.id && @current_user.friends.exclude?(@user) %>
					<%= bootstrap_form_for @friend, :method => 'post' do |f| %>
					<%=f.hidden_field 'user_id', :value => @user.id %>
					<%= f.submit 'Follow', class: 'btn btn-default follow' %> 
				<% end %>
			<% elsif @current_user && @current_user.id != @user.id && @current_user.friends.include?(@user)%>
				<h3>You are Following <%= @user.name %></h3>
			<% else %>
			<% end %>
	</div>

	<div class='row profile-content'>
		<div class='col-md-4'>
			<%= cl_image_tag(@user.cloud_id, :width => 400, :height => 400, :crop => :fill, :gravity => :face) %>
				<% if(@current_user && @current_user.id == @user.id) %>
					<%= link_to '<i class="fa fa-trash-o"></i> Delete Profile'.html_safe, '#delete', 'data-toggle' => 'modal', 'data-target' => '#delete', class: 'btn btn-default', id: 'delete'%>
					<%= link_to '<i class="fa fa-pencil"></i> Edit Profile'.html_safe, '#edit', 'data-toggle' => 'modal', 'data-target' => '#edit', class: 'btn btn-default', id: 'edit'%>
				<% end %>
				<div class='friends'>
					<% if @user.friends.length == 0 %>
					<% else %>
						<h4><%= @user.name %> is Following: </h4>
						<ul>
							<% @friends.each do |friend| %>
								<li><a href='<%= friend.id %>'><%= friend.name %></a></li>
							<% end %>
						</ul>
					<% end %>
					<% if @followers.length == 0 %>
					<% else %>
						<h4><%= @user.name %> is Followed By: </h4>
							<ul>
								<% @followers.each do |follower| %>
								<li><a href='<%= follower.user.id %>'><%= follower.user.name %></a></li>
							<% end %>
						</ul>
					<% end %>
				</div>
		</div>
		<div class='col-md-8'>
			<table id="user-calendar"></table>
		</div>
	</div>
</div>